name: party_proje_deneme
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  http: ^0.13.5
  image_picker: ^0.8.7+5
  mask_text_input_formatter: ^2.3.0
  motion_toast: ^2.6.7
  percent_indicator: ^4.2.3
  shared_preferences: ^2.1.0
  toast: ^0.3.0

  loading_animation_widget: ^1.2.0+4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf




  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
